### ISSUE TITLE
404 when loading a sub-path directly

### ISSUE THREAD

**Issue by ivansieder** [SaraVieira/speaker-info#1]
Opening https://speaker.iamsaravieira.com/ and navigating to /talks or /videos by clicking in the navigation works perfectly, but opening https://speaker.iamsaravieira.com/talks directly in a separate tab or hitting F5 on a sub-page seems to give a 404.

**Comment by SaraVieira** [comment]
Fixed with 2f30ac47b92d9bd8bbcadbc68142205d34fa38e0 !
Thank you :)
