### ISSUE TITLE
Photo's label is overflowing the image

### ISSUE THREAD

**Issue by nunofgm** [SaraVieira/speaker-info#3]
<img width="673" alt="captura de ecra 2018-08-16 as 16 48 43" src="https://user-images.githubusercontent.com/4692114/44219566-4aeb1a00-a174-11e8-893f-a7eb3aa7c3d2.png">

**Comment by SaraVieira** [comment]
I removed that, it's not needed so fixed, I guess ? ahah

**Comment by nunofgm** [comment]
true story :p

**Comment by SaraVieira** [comment]
People can save image as ahah

**Comment by nunofgm** [comment]
Or inspect the html to find the source :)
